/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv` (hash: ca0170e71d82da2e196808c4e63c8525)
// Runtime types generated with workerd@1.20250416.0 2024-12-30 nodejs_compat
declare namespace Cloudflare {
	interface Env {
		NEXTJS_ENV: string;
		DB: D1Database;
		WORKER_SELF_REFERENCE: Fetcher;
		ASSETS: Fetcher;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
